surname = input("Введите фамилию: ")
name = input("Введите имя: ")
group = input("Введите группу: ")
city = input("Введите город: ")
age = int(input("Сколько полных лет: "))
favorite_sub = input("Введите любимый предмет: ")
hours = float(input("Введите количество часов подготовки в неделю: "))

print()
print("=== Карточка студента ===")
print(f"Полное имя: {name} {surname}")
print(f"Группа: {group}")
print(f"Город: {city}")
print(f"Любимый предмет: {favorite_sub}")
print(f"Возраст: {age}")
print(f"Возраст через 4 года: {age + 4}")
print(f"Подготовка за 4 недели: {hours * 4:.2f} ч")
print(f"Среднее в день: {hours / 7:.2f} ч")